workflows:
  android-app:
    name: Android App Build
    max_build_duration: 60
    environment:
      android_signing:
        keystore:
          create: true  # Creates a temporary debug keystore
          name: temp_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.SLTS"
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
      java: 11
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Set up gradle permissions
        script: |
          chmod +x gradlew

      - name: Build Android debug APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
      
    publishing:
      email:
        recipients:
          - ${EMAIL_ADDRESS}
        notify:
          success: true
          failure: true
          
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: true
