workflows:
  android-app:
    name: Android App Build
    max_build_duration: 60
    environment:
      android_signing:
        - keystoreFile: release.keystore
          keystorePassword: ${KEYSTORE_PASSWORD}
          keyAlias: ${KEY_ALIAS}
          keyPassword: ${KEY_PASSWORD}
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.SLTS"
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
      java: 11
    scripts:
      - name: Create debug keystore
        script: |
          keytool -genkeypair \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            -alias androiddebugkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US" \
            -v

      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Set up gradle permissions
        script: |
          chmod +x gradlew

      - name: Build Android debug APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
      
    publishing:
      email:
        recipients:
          - ${EMAIL_ADDRESS}  # Will be set in Codemagic UI
        notify:
          success: true
          failure: true
          
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: true
